"""Add billing_cycles table and billing_cycle_id FK

Revision ID: 010860a68cea
Revises: e5349bc4ddb8
Create Date: 2026-02-15 03:26:55.760869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010860a68cea'
down_revision = 'e5349bc4ddb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )

    billing_cycle_table = sa.table(
        'billing_cycles',
        sa.column('code', sa.String(length=20)),
        sa.column('name', sa.String(length=50)),
        sa.column('display_order', sa.Integer()),
        sa.column('is_active', sa.Boolean()),
    )

    op.bulk_insert(
        billing_cycle_table,
        [
            {'code': 'monthly', 'name': 'Monthly', 'display_order': 1, 'is_active': True},
            {'code': 'yearly', 'name': 'Yearly', 'display_order': 2, 'is_active': True},
            {'code': 'lifetime', 'name': 'Lifetime', 'display_order': 3, 'is_active': True},
        ],
    )

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_cycle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'billing_cycles', ['billing_cycle_id'], ['id'])

    op.execute(
        """
        UPDATE user_subscriptions us
        SET billing_cycle_id = bc.id
        FROM billing_cycles bc
        WHERE bc.code = COALESCE(us.billing_cycle, 'monthly')
        """
    )

    op.execute(
        """
        UPDATE user_subscriptions
        SET billing_cycle_id = (SELECT id FROM billing_cycles WHERE code = 'monthly')
        WHERE billing_cycle_id IS NULL
        """
    )

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('billing_cycle_id', existing_type=sa.Integer(), nullable=False)
        batch_op.drop_column('billing_cycle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_cycle', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    op.execute(
        """
        UPDATE user_subscriptions us
        SET billing_cycle = bc.code
        FROM billing_cycles bc
        WHERE us.billing_cycle_id = bc.id
        """
    )

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('billing_cycle_id')

    op.drop_table('billing_cycles')
    # ### end Alembic commands ###
