"""Modified models: Added superadmin, admin and other functionalities

Revision ID: 79734db3c553
Revises: 
Create Date: 2024-09-23 03:07:58.386106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79734db3c553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add the role column with a default value
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    
    # If you need to set different roles for existing users, you can do it here
    # op.execute("UPDATE users SET role = 'admin' WHERE username = 'admin@example.com'")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
